Repository MicrosoftDocs/visualstudio-docs.zh-cn, pull requests merged in 2019-03, with the labels that each got.

#112 Update designing-xaml-in-visual-studio.md
  docs/designers/designing-xaml-in-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#113 Update getting-started-with-visual-studio-tools-for-unity.md
  docs/cross-platform/getting-started-with-visual-studio-tools-for-unity.md
Labels: Linguistic Suggestion, Partially Accepted

#114 Update unity-scripting-upgrade.md
  docs/cross-platform/unity-scripting-upgrade.md
Labels: Accepted, Linguistic Suggestion

#118 Update walkthrough-using-msbuild.md
  docs/msbuild/walkthrough-using-msbuild.md
Labels: Accepted, In Progress

#120 密钥 -> 键
  docs/msbuild/msbuild-properties.md
Labels: Accepted, In Progress

#119 Update common-msbuild-project-properties.md
  docs/msbuild/common-msbuild-project-properties.md
Labels: Accepted, In Progress

#117 Update msbuild-reserved-and-well-known-properties.md
  docs/msbuild/msbuild-reserved-and-well-known-properties.md
Labels: Accepted

#116 Update walkthrough-using-msbuild.md
  docs/msbuild/walkthrough-using-msbuild.md
Labels: Accepted, Linguistic Suggestion
